name: build-and-deploy-rominronin

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: hydephp/action@master
        with:
          deploy-to: "pages"